HYBRIS_HOST:
  ms: "http://hybris.ms"
  dev: "http://hybris.dev"
  preprod: "aldrynho.preprod"
  qa1: "http://hybris.ms"
HYBRIS_PORT:
  ms: "http://hybris.ms"
  dev: "http://hybris.dev"
  preprod: "5555"
  qa1: "http://hybris.ms"

ENV_X:
  ms: "sasas"
  dev: "sasasasas"
  qa1: "sassaassaas"
